name: test

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  schedule:
    - cron: "00 00 * * 3"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    environment: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TRIVY_VERSION: v0.68.2
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.5
        with:
          version: ${{ env.TRIVY_VERSION }}
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Run CI tests
        run: |
          make ci-test
